### ISSUE TITLE
How to navigate to the project?

### ISSUE THREAD

**Issue by vedantbahel** [dhindrik/MushroomDetector#1]
I am creating a chest X-ray based classification model. I have imported the tflite and label file and also have created "TensorFlowClassifier.cs" and "ImageClassificationModel.cs" in App.Android

In the main folder, I have a home page with test now button. How do I link it up with the model?

**Comment by dhindrik** [comment]
I have bind MainViewModel to it. I use [TinyMvvm](https://github.com/TinyStuff/TinyMvvm) so I set it as a TypeArgument to MainView.
https://github.com/dhindrik/MushroomDetector/blob/d22e2f8a6710e96b6909c7b9820a9a06e5859ea7/MushroomDetector/Views/MainView.xaml#L5

Then I am doing the navigation here: https://github.com/dhindrik/MushroomDetector/blob/d22e2f8a6710e96b6909c7b9820a9a06e5859ea7/MushroomDetector/ViewModels/MainViewModel.cs#L109

**Comment by vedantbahel** [comment]
Alright! Tack!!
